In [74]:
import numpy as np
import pandas as pd

from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix


In [75]:
model = SVC(kernel='linear', C=100)

In [76]:
df = pd.read_csv('features.csv')

In [77]:
df.head()

Unnamed: 0    lesion_id      image_id   dx    dx_type   age     sex  \
0        4349  HAM_0000550  ISIC_0024306   nv  follow_up  45.0    male   
1        4263  HAM_0003577  ISIC_0024307   nv  follow_up  50.0    male   
2        4217  HAM_0001477  ISIC_0024308   nv  follow_up  55.0  female   
3        3587  HAM_0000484  ISIC_0024309   nv  follow_up  40.0    male   
4        1451  HAM_0003350  ISIC_0024310  mel      histo  60.0    male   

      localization   contrast  dissimilarity    ...     average_red  \
0            trunk  24.014902       3.069379    ...      214.742830   
1  lower extremity  30.136113       3.191185    ...      216.408637   
2            trunk  41.095028       4.274612    ...      211.505348   
3            trunk  12.082754       2.573382    ...      193.472681   
4            chest  67.513619       5.757603    ...      201.125259   

   average_green  average_blue  moment_1  moment_2  moment_3  moment_4  \
0     117.623078    118.454056  1.163379  1.382237  2.829335  2.813571   
1     124.305130    130.559900  1.118366  1.293264  2.535354  2.515856   
2     128.136615    127.854930  1.480798  2.217678  4.343567  4.375000   
3     107.059463    117.562107  1.056819  1.227700  2.319562  2.259257   
4     133.741378    130.974178  0.324694  0.107135  0.202398  0.204181   

    moment_5  moment_6  moment_7  
0   7.935344  3.307396  0.217670  
1   6.353954  2.861035  0.026798  
2  19.071113  6.515033 -0.154898  
3   5.169826  2.502097  0.146991  
4   0.041503  0.066831 -0.000623  

[5 rows x 23 columns]

In [78]:
df = df.dropna()

In [90]:
df_target = pd.DataFrame(df['dx'])
df_target_two = pd.DataFrame(df['dx'] == 'akiec' or df['dx'] == 'mel' or df['dx'] == 'bcc')

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [91]:
df_target_two.head()

dx
0   True
1   True
2   True
3   True
4  False

In [80]:
df_feat = df[['age', 'contrast', 'contrast', 'dissimilarity', 'homogeneity', 'energy','correlation', 'average_red', 'average_green', 'average_blue', 'moment_1', 'moment_2', 'moment_3', 'moment_4','moment_5', 'moment_6', 'moment_7']].copy()

In [70]:
df_feat.head(5)

age   contrast   contrast  dissimilarity  homogeneity    energy  \
0  45.0  24.014902  24.014902       3.069379     0.307001  0.043835   
1  50.0  30.136113  30.136113       3.191185     0.303528  0.043541   
2  55.0  41.095028  41.095028       4.274612     0.251319  0.032048   
3  40.0  12.082754  12.082754       2.573382     0.320591  0.042877   
4  60.0  67.513619  67.513619       5.757603     0.179977  0.024888   

   correlation  average_red  average_green  average_blue  moment_1  moment_2  \
0     0.987888   214.742830     117.623078    118.454056  1.163379  1.382237   
1     0.959360   216.408637     124.305130    130.559900  1.118366  1.293264   
2     0.991983   211.505348     128.136615    127.854930  1.480798  2.217678   
3     0.989450   193.472681     107.059463    117.562107  1.056819  1.227700   
4     0.966229   201.125259     133.741378    130.974178  0.324694  0.107135   

   moment_3  moment_4   moment_5  moment_6  moment_7  
0  2.829335  2.813571   7.935344  3.307396  0.217670  
1  2.535354  2.515856   6.353954  2.861035  0.026798  
2  4.343567  4.375000  19.071113  6.515033 -0.154898  
3  2.319562  2.259257   5.169826  2.502097  0.146991  
4  0.202398  0.204181   0.041503  0.066831 -0.000623

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10015 entries, 0 to 10014
Data columns (total 23 columns):
Unnamed: 0       10015 non-null int64
lesion_id        10015 non-null object
image_id         10015 non-null object
dx               10015 non-null object
dx_type          10015 non-null object
age              9958 non-null float64
sex              10015 non-null object
localization     10015 non-null object
contrast         10015 non-null float64
dissimilarity    10015 non-null float64
homogeneity      10015 non-null float64
energy           10015 non-null float64
correlation      10015 non-null float64
average_red      10015 non-null float64
average_green    10015 non-null float64
average_blue     10015 non-null float64
moment_1         10015 non-null float64
moment_2         10015 non-null float64
moment_3         10015 non-null float64
moment_4         10015 non-null float64
moment_5         10015 non-null float64
moment_6         10015 non-null float64
moment_7         100

In [73]:
df_target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10015 entries, 0 to 10014
Data columns (total 1 columns):
dx    10015 non-null object
dtypes: object(1)
memory usage: 78.3+ KB


In [81]:
X_train, X_test, y_train, y_test = train_test_split(df_feat, np.ravel(df_target), test_size=0.30, random_state=101)

In [82]:
model.fit(X_train,y_train)

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [83]:
predictions = model.predict(X_test)

In [84]:
print(confusion_matrix(y_test,predictions))

[[   5    4   13    0    3   67    0]
 [   5   22   24    0    6   90    0]
 [   6   17   90    1   31  185    0]
 [   0    4    4    0    0   32    0]
 [   6    1   53    0   65  191    0]
 [   4   10   45    1   42 1906    0]
 [   0    2    1    0    1   51    0]]


In [85]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

       akiec       0.19      0.05      0.08        92
         bcc       0.37      0.15      0.21       147
         bkl       0.39      0.27      0.32       330
          df       0.00      0.00      0.00        40
         mel       0.44      0.21      0.28       316
          nv       0.76      0.95      0.84      2008
        vasc       0.00      0.00      0.00        55

   micro avg       0.70      0.70      0.70      2988
   macro avg       0.31      0.23      0.25      2988
weighted avg       0.62      0.70      0.64      2988



/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [93]:
X_train, X_test, y_train2, y_test2 = train_test_split(df_feat, np.ravel(df_target_two), test_size=0.30, random_state=101)

In [94]:
model.fit(X_train,y_train2)

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [95]:
predictions = model.predict(X_test)

In [96]:
print(confusion_matrix(y_test,predictions))

[[ 612  368]
 [ 259 1749]]


In [97]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

       False       0.70      0.62      0.66       980
        True       0.83      0.87      0.85      2008

   micro avg       0.79      0.79      0.79      2988
   macro avg       0.76      0.75      0.75      2988
weighted avg       0.79      0.79      0.79      2988



In [99]:
predictions2 = model.predict(X_train)

In [101]:
print(confusion_matrix(y_train,predictions2))

[[1556  762]
 [ 581 4071]]


In [103]:
print(classification_report(y_train,predictions2))

              precision    recall  f1-score   support

       False       0.73      0.67      0.70      2318
        True       0.84      0.88      0.86      4652

   micro avg       0.81      0.81      0.81      6970
   macro avg       0.79      0.77      0.78      6970
weighted avg       0.80      0.81      0.81      6970

