In [797]:
import numpy as np
import pandas as pd
import seaborn as sns
%matplotlib inline

from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler



In [988]:
model = SVC(kernel='rbf', C=50, gamma = 'scale', probability = True)

In [810]:
#df = pd.read_csv('features.csv')
#df = pd.read_csv('with_validation.csv', sep=';')
#df = pd.read_csv('processed_all.csv')
df = pd.read_csv('features_all.csv')


In [505]:
#drop here because Fabi used histogram equalization
df = df.drop(['contrast', 'dissimilarity', 'homogeneity', 'energy', 'correlation'],axis = 1)

In [506]:
df3 = pd.read_csv('features_big.csv')

In [507]:
# drop here because Malte used masking for calculating average color
df3 = df3.drop(['average_red', 'average_green', 'average_blue'], axis = 1)

In [508]:
df3.head()

Moment_R_L00  Moment_R_L01  Moment_R_L02  Moment_R_L10  Moment_R_L11  \
0      0.000578     -3.125691    -16.983755    -29.627738     -2.659856   
1      0.000148      6.620587    -57.724036     -5.835733     -6.146287   
2      0.000189     23.620562    -51.707425    -32.906473     10.581304   
3      0.000311    -16.095788    -77.088365    -13.184954      1.303120   
4      0.000411      6.413269     50.663407     67.091066    -33.535822   

   Moment_R_L12  Moment_R_L20  Moment_R_L21  Moment_R_L22  Moment_G_L00  \
0     -8.371072    -74.668856    -11.351595    -69.762741      0.000637   
1      5.408704   -127.847081    -15.500430     -1.895868      0.000881   
2      5.893859    -74.381919    -44.328496    -60.476961      0.000311   
3     -4.938602   -117.251672     -0.052012     23.886053      0.000204   
4    -42.954445     26.455474    -24.612728   -123.307385      0.000022   

      ...       Moment_B_L11  Moment_B_L12  Moment_B_L20  Moment_B_L21  \
0     ...           4.689851    -15.172860    -13.917333      2.193507   
1     ...          -3.553159      0.646947    -90.186046     -3.469786   
2     ...          21.263483     21.453625    -25.047003    -15.558758   
3     ...           5.498728    -16.035910    -83.199683    -15.145891   
4     ...         -16.815326    -35.783436     34.858271    -30.933713   

   Moment_B_L22    contrast  dissimilarity  homogeneity    energy  correlation  
0    -72.617370  465.386540      14.615087     0.106273  0.009928     0.954047  
1    -78.328826  304.521999      11.465017     0.147548  0.012939     0.970505  
2    -70.802885  516.337480      15.191007     0.102377  0.009613     0.948698  
3    -13.144988  751.802163      17.235548     0.121107  0.011567     0.926096  
4   -110.959324  136.559078       6.558796     0.219156  0.015555     0.987239  

[5 rows x 32 columns]

In [509]:
ids = pd.read_csv('image_ids.csv')

In [510]:
ids = ids.drop(['lesion_id', 'dx', 'dx_type', 'age', 'sex', 'localization'], axis = 1)

In [511]:
merge_df = df3.join(ids, how='outer')

In [512]:
merge_df.head()

Moment_R_L00  Moment_R_L01  Moment_R_L02  Moment_R_L10  Moment_R_L11  \
0      0.000578     -3.125691    -16.983755    -29.627738     -2.659856   
1      0.000148      6.620587    -57.724036     -5.835733     -6.146287   
2      0.000189     23.620562    -51.707425    -32.906473     10.581304   
3      0.000311    -16.095788    -77.088365    -13.184954      1.303120   
4      0.000411      6.413269     50.663407     67.091066    -33.535822   

   Moment_R_L12  Moment_R_L20  Moment_R_L21  Moment_R_L22  Moment_G_L00  \
0     -8.371072    -74.668856    -11.351595    -69.762741      0.000637   
1      5.408704   -127.847081    -15.500430     -1.895868      0.000881   
2      5.893859    -74.381919    -44.328496    -60.476961      0.000311   
3     -4.938602   -117.251672     -0.052012     23.886053      0.000204   
4    -42.954445     26.455474    -24.612728   -123.307385      0.000022   

       ...       Moment_B_L12  Moment_B_L20  Moment_B_L21  Moment_B_L22  \
0      ...         -15.172860    -13.917333      2.193507    -72.617370   
1      ...           0.646947    -90.186046     -3.469786    -78.328826   
2      ...          21.453625    -25.047003    -15.558758    -70.802885   
3      ...         -16.035910    -83.199683    -15.145891    -13.144988   
4      ...         -35.783436     34.858271    -30.933713   -110.959324   

     contrast  dissimilarity  homogeneity    energy  correlation      image_id  
0  465.386540      14.615087     0.106273  0.009928     0.954047  ISIC_0027419  
1  304.521999      11.465017     0.147548  0.012939     0.970505  ISIC_0025030  
2  516.337480      15.191007     0.102377  0.009613     0.948698  ISIC_0026769  
3  751.802163      17.235548     0.121107  0.011567     0.926096  ISIC_0025661  
4  136.559078       6.558796     0.219156  0.015555     0.987239  ISIC_0031633  

[5 rows x 33 columns]

In [513]:
df = merge_df.set_index('image_id').join(df.set_index('image_id'))

In [806]:
df.head()

area  area_variance01  area_variance02  area_variance03  \
image_id                                                                   
ISIC_0024306  55753.0       113.617597       184.429171       143.167927   
ISIC_0024307  51264.0        60.152981       150.014751       193.760493   
ISIC_0024308  80633.5        34.955079       181.790820       145.373889   
ISIC_0024309  55425.5       173.797075       171.508705       152.693182   
ISIC_0024310  42664.5        53.887443       130.269553       158.705142   

              area_variance1  area_variance2  area_variance3  average_blue  \
image_id                                                                     
ISIC_0024306       85.325693       14.157758       29.372298      0.793936   
ISIC_0024307       83.918039       17.260601       12.629358      1.240442   
ISIC_0024308       69.106006       31.471933       36.710583      1.680835   
ISIC_0024309        2.037120       13.166800       13.236745      1.625546   
ISIC_0024310       77.814072       32.021363       37.005539      0.812584   

              average_blue2  average_green    ...          nu03      nu12  \
image_id                                      ...                           
ISIC_0024306     214.742830       0.793936    ...     -0.004953 -0.004660   
ISIC_0024307     216.408637       1.240442    ...     -0.002422  0.006293   
ISIC_0024308     211.505348       1.680835    ...      0.002476  0.004335   
ISIC_0024309     193.472681       1.625546    ...     -0.002172 -0.002769   
ISIC_0024310     201.125259       0.812584    ...      0.004127  0.006592   

                  nu20      nu21      nu30    perimeter              symmetry  \
image_id                                                                        
ISIC_0024306  0.066802  0.001744  0.001999  1175.283393   0.05628441306633003   
ISIC_0024307  0.087290  0.001290 -0.005850  1348.253955   0.15352604100927575   
ISIC_0024308  0.140067  0.003432 -0.000241  1347.692555  0.056716459615777426   
ISIC_0024309  0.109403  0.004772  0.004881  1163.844795   0.10369413971984681   
ISIC_0024310  0.148071 -0.012777 -0.026188  1600.319971    0.2042172531130576   

               dx  validation  malignant  
image_id                                  
ISIC_0024306   nv           0          0  
ISIC_0024307   nv           0          0  
ISIC_0024308   nv           0          0  
ISIC_0024309   nv           0          0  
ISIC_0024310  mel           0          1  

[5 rows x 43 columns]

In [516]:
df.to_csv('features_all_together.csv')

In [811]:
df = df.dropna()

In [812]:
df_train = df[df['validation'] == 0]
df_test = df[df['validation'] == 1]

y_train = pd.DataFrame(df_train['malignant'] == 1)
y_test = pd.DataFrame(df_test['malignant'] == 1)

# All numeric features

In [521]:
df.head()

Moment_R_L00  Moment_R_L01  Moment_R_L02  Moment_R_L10  \
image_id                                                               
ISIC_0027419      0.000578     -3.125691    -16.983755    -29.627738   
ISIC_0025030      0.000148      6.620587    -57.724036     -5.835733   
ISIC_0026769      0.000189     23.620562    -51.707425    -32.906473   
ISIC_0025661      0.000311    -16.095788    -77.088365    -13.184954   
ISIC_0031633      0.000411      6.413269     50.663407     67.091066   

              Moment_R_L11  Moment_R_L12  Moment_R_L20  Moment_R_L21  \
image_id                                                               
ISIC_0027419     -2.659856     -8.371072    -74.668856    -11.351595   
ISIC_0025030     -6.146287      5.408704   -127.847081    -15.500430   
ISIC_0026769     10.581304      5.893859    -74.381919    -44.328496   
ISIC_0025661      1.303120     -4.938602   -117.251672     -0.052012   
ISIC_0031633    -33.535822    -42.954445     26.455474    -24.612728   

              Moment_R_L22  Moment_G_L00    ...          nu03      nu12  \
image_id                                    ...                           
ISIC_0027419    -69.762741      0.000637    ...      0.014579  0.023919   
ISIC_0025030     -1.895868      0.000881    ...     -0.048263  0.023418   
ISIC_0026769    -60.476961      0.000311    ...      0.017578 -0.016207   
ISIC_0025661     23.886053      0.000204    ...     -0.056763  0.019802   
ISIC_0031633   -123.307385      0.000022    ...      0.002529 -0.007409   

                  nu20      nu21      nu30    perimeter             symmetry  \
image_id                                                                       
ISIC_0027419  0.061852 -0.006439 -0.005693  1179.165643   0.9770473925852277   
ISIC_0025030  0.125249  0.005926 -0.023605   481.480229   161.07803921906105   
ISIC_0026769  0.202239  0.000484  0.014633  3052.164768   0.9591750731310495   
ISIC_0025661  0.081058  0.006778 -0.012322   494.492422  0.11282341025738685   
ISIC_0031633  0.124105  0.002641  0.002093  2153.106769  0.17135336578585886   

               dx  validation  malignant  
image_id                                  
ISIC_0027419  bkl           1          0  
ISIC_0025030  bkl           1          0  
ISIC_0026769  bkl           0          0  
ISIC_0025661  bkl           0          0  
ISIC_0031633  bkl           0          0  

[5 rows x 70 columns]

In [938]:
X_train = df_train.drop(['dx', 'validation', 'malignant'], axis = 1)

X_test = df_test.drop(['dx', 'validation', 'malignant'], axis = 1)

In [989]:
X_train = df_train.drop(['dx', 'validation', 'malignant', 'image_id'], axis = 1)

X_test = df_test.drop(['dx', 'validation', 'malignant','image_id'], axis = 1)

In [990]:
min_max_scaler = preprocessing.MinMaxScaler()

X_train = pd.DataFrame(min_max_scaler.fit_transform(X_train), columns=X_train.columns)
X_test = pd.DataFrame(min_max_scaler.fit_transform(X_test), columns=X_test.columns)

/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:36: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial)
/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype float64, object were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)
/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:36: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial)
/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:36: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial)
/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype float64, object were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)
/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:

In [991]:
X_train = preprocessing.scale(X_train)
X_test  = preprocessing.scale(X_test)

In [992]:
#https://www.youtube.com/watch?v=RXFnwCRb-is

from sklearn.feature_selection import SelectKBest

select = SelectKBest(f_classif , k=30)
select.fit(X_train, np.ravel(y_train))
X_train = pd.DataFrame(select.transform(X_train))
X_test = pd.DataFrame(select.transform(X_test))

In [142]:
#This is only needed if we don't have a validation set splitting given
#X_train, X_test, y_train, y_test = train_test_split(df_feat, np.ravel(df_target), test_size=0.30, random_state=101)

In [993]:
model.fit(X_train,np.ravel(y_train))

SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [994]:
predictions = model.predict(X_test)

In [998]:
prediction_probabilities = model.predict_proba(X_test)

In [999]:
prediction_probabilities

array([[0.80410834, 0.19589166],
       [0.77326374, 0.22673626],
       [0.54034837, 0.45965163],
       ...,
       [0.93946062, 0.06053938],
       [0.71986354, 0.28013646],
       [0.66007318, 0.33992682]])

In [1000]:
result = pd.DataFrame(prediction_probabilities)

In [1002]:
result.head()

0         1
0  0.804108  0.195892
1  0.773264  0.226736
2  0.540348  0.459652
3  0.840546  0.159454
4  0.961247  0.038753

In [1010]:
image_label = pd.DataFrame(df_test['image_id'])

In [1003]:
image_label= image_label.reset_index(drop=True)

In [1011]:
image_label.head()

image_id
6   ISIC_0024312
11  ISIC_0024317
12  ISIC_0024318
18  ISIC_0024324
22  ISIC_0024328

In [1005]:
to_csv = image_label.join(result, how='outer')

In [1008]:
to_csv.to_csv('binary_classification', index = False)

In [1009]:
to_csv.head()

image_id         0         1
0  ISIC_0024312  0.804108  0.195892
1  ISIC_0024317  0.773264  0.226736
2  ISIC_0024318  0.540348  0.459652
3  ISIC_0024324  0.840546  0.159454
4  ISIC_0024328  0.961247  0.038753

In [995]:
confusion = confusion_matrix(y_test,predictions)
print(confusion)


[[1772  246]
 [ 281  212]]


In [981]:
#print(classification_report(y_test,predictions))

In [997]:
print(metrics.accuracy_score(y_test, predictions)) #accuracy
print(1 - metrics.accuracy_score(y_test, predictions)) # classification error
print(metrics.recall_score(y_test, predictions, average=None)) #specificity and sensitivity
print(metrics.precision_score(y_test, predictions, average=None))
print(metrics.f1_score(y_test, predictions, average=None))

0.7901234567901234
0.2098765432098766
[0.87809713 0.43002028]
[0.86312713 0.4628821 ]
[0.87054778 0.44584648]


In [824]:
predictions = model.predict(X_train)

Check with train data if overfitting?

In [825]:
print(confusion_matrix(y_train,predictions))

[[5943  100]
 [ 481  980]]


In [826]:
print(classification_report(y_train,predictions))

              precision    recall  f1-score   support

       False       0.93      0.98      0.95      6043
        True       0.91      0.67      0.77      1461

   micro avg       0.92      0.92      0.92      7504
   macro avg       0.92      0.83      0.86      7504
weighted avg       0.92      0.92      0.92      7504



# Gridsearch

In [468]:
param_grid = {'C': [1, 10, 100, 1000], 'gamma': [100,10,1,0.1,0.01, 'scale'], 'kernel': ['rbf']} 

In [469]:
from sklearn.model_selection import GridSearchCV

In [470]:
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)

In [471]:
# Could take some time
grid.fit(X_train,np.ravel(y_train))

/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Fitting 3 folds for each of 24 candidates, totalling 72 fits
[CV] C=1, gamma=100, kernel=rbf ......................................
[CV]  C=1, gamma=100, kernel=rbf, score=0.8053557154276578, total=   2.4s
[CV] C=1, gamma=100, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    3.8s remaining:    0.0s


[CV]  C=1, gamma=100, kernel=rbf, score=0.8052778888444622, total=   2.3s
[CV] C=1, gamma=100, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    7.6s remaining:    0.0s


[CV]  C=1, gamma=100, kernel=rbf, score=0.8052778888444622, total=   2.3s
[CV] C=1, gamma=10, kernel=rbf .......................................
[CV]  C=1, gamma=10, kernel=rbf, score=0.8053557154276578, total=   3.4s
[CV] C=1, gamma=10, kernel=rbf .......................................
[CV]  C=1, gamma=10, kernel=rbf, score=0.8052778888444622, total=   3.2s
[CV] C=1, gamma=10, kernel=rbf .......................................
[CV]  C=1, gamma=10, kernel=rbf, score=0.8052778888444622, total=   3.1s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV]  C=1, gamma=1, kernel=rbf, score=0.8053557154276578, total=   3.6s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV]  C=1, gamma=1, kernel=rbf, score=0.8052778888444622, total=   3.7s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV]  C=1, gamma=1, kernel=rbf, score=0.8052778888444622, total=   3.7s
[CV] C=1, gamma=0.1, kernel=rbf .................................

[CV]  C=1000, gamma=10, kernel=rbf, score=0.8052778888444622, total=   3.4s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV]  C=1000, gamma=1, kernel=rbf, score=0.8053557154276578, total=   4.6s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV]  C=1000, gamma=1, kernel=rbf, score=0.8052778888444622, total=   4.5s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV]  C=1000, gamma=1, kernel=rbf, score=0.8052778888444622, total=   4.8s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV]  C=1000, gamma=0.1, kernel=rbf, score=0.7881694644284573, total=   3.0s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV]  C=1000, gamma=0.1, kernel=rbf, score=0.8096761295481807, total=   3.1s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV]  C=1000, gamma=0.1, kernel=rbf, score=0.641343462614954, total=   3.0s
[CV] C=1000, gamma=0.01, kernel=rbf .......

[Parallel(n_jobs=1)]: Done  72 out of  72 | elapsed:  5.1min finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'C': [1, 10, 100, 1000], 'gamma': [100, 10, 1, 0.1, 0.01, 'scale'], 'kernel': ['rbf']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [472]:
grid.best_params_

{'C': 1, 'gamma': 100, 'kernel': 'rbf'}

In [473]:
grid.best_estimator_

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=100, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [474]:
grid_predictions = grid.predict(X_test)

In [475]:
print(confusion_matrix(y_test,grid_predictions))

[[2018    0]
 [ 493    0]]


# Random Forrest

In [615]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [616]:
predictions = dtree.predict(X_test)

In [617]:
print(confusion_matrix(y_test,predictions))

[[1657  361]
 [ 305  188]]
